from common import clean_str

COUNTRY_INFO = {
    "US": ("United States", "Americas"),
    "CA": ("Canada", "Americas"),
    "MX": ("Mexico", "Americas"),
    "BR": ("Brazil", "Americas"),
    "CL": ("Chile", "Americas"),
    "GB": ("United Kingdom", "Europe"),
    "IE": ("Ireland", "Europe"),
    "FR": ("France", "Europe"),
    "DE": ("Germany", "Europe"),
    "NL": ("Netherlands", "Europe"),
    "BE": ("Belgium", "Europe"),
    "LU": ("Luxembourg", "Europe"),
    "IT": ("Italy", "Europe"),
    "ES": ("Spain", "Europe"),
    "PT": ("Portugal", "Europe"),
    "AT": ("Austria", "Europe"),
    "CH": ("Switzerland", "Europe"),
    "SE": ("Sweden", "Europe"),
    "NO": ("Norway", "Europe"),
    "DK": ("Denmark", "Europe"),
    "FI": ("Finland", "Europe"),
    "PL": ("Poland", "Europe"),
    "CZ": ("Czechia", "Europe"),
    "SK": ("Slovakia", "Europe"),
    "HU": ("Hungary", "Europe"),
    "RO": ("Romania", "Europe"),
    "GR": ("Greece", "Europe"),
    "HR": ("Croatia", "Europe"),
    "SI": ("Slovenia", "Europe"),
    "RS": ("Serbia", "Europe"),
    "TR": ("Turkey", "Europe"),
    "AU": ("Australia", "Oceania"),
    "NZ": ("New Zealand", "Oceania"),
    "JP": ("Japan", "Asia"),
    "KR": ("South Korea", "Asia"),
    "CN": ("China", "Asia"),
    "HK": ("Hong Kong", "Asia"),
    "TW": ("Taiwan", "Asia"),
    "SG": ("Singapore", "Asia"),
    "MY": ("Malaysia", "Asia"),
    "TH": ("Thailand", "Asia"),
    "ID": ("Indonesia", "Asia"),
    "PH": ("Philippines", "Asia"),
    "VN": ("Vietnam", "Asia"),
    "IN": ("India", "Asia"),
    "AE": ("United Arab Emirates", "Middle East"),
    "SA": ("Saudi Arabia", "Middle East"),
    "IL": ("Israel", "Middle East"),
    "ZA": ("South Africa", "Africa"),
    "EG": ("Egypt", "Africa"),
}


def build_market(country_code, currency):
    code = clean_str(country_code)
    name, region = COUNTRY_INFO.get(code, (code, None))
    return {
        "_id": code,
        "country_code": code,
        "name": name,
        "region": region,
        "currency": clean_str(currency),
    }
